### Finding Correlation Matrix

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('milknew.csv')
print(df)

       pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0     6.6          35      1     0     1          0     254    high
1     6.6          36      0     1     0          1     253    high
2     8.5          70      1     1     1          1     246     low
3     9.5          34      1     1     0          1     255     low
4     6.6          37      0     0     0          0     255  medium
...   ...         ...    ...   ...   ...        ...     ...     ...
1054  6.7          45      1     1     0          0     247  medium
1055  6.7          38      1     0     1          0     255    high
1056  3.0          40      1     1     1          1     255     low
1057  6.8          43      1     0     1          0     250    high
1058  8.6          55      0     1     1          1     255     low

[1059 rows x 8 columns]


In [4]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

### Confusion Matrix

In [20]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X

array([[  6.6,  35. ,   1. , ...,   1. ,   0. , 254. ],
       [  6.6,  36. ,   0. , ...,   0. ,   1. , 253. ],
       [  8.5,  70. ,   1. , ...,   1. ,   1. , 246. ],
       ...,
       [  3. ,  40. ,   1. , ...,   1. ,   1. , 255. ],
       [  6.8,  43. ,   1. , ...,   1. ,   0. , 250. ],
       [  8.6,  55. ,   0. , ...,   1. ,   1. , 255. ]])

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [22]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [23]:
y_predlr = lr.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predlr)
cm

array([[40, 14,  0],
       [ 4, 77,  2],
       [ 9,  1, 65]], dtype=int64)

In [26]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import mean_absolute_error
gb = GradientBoostingClassifier(n_estimators = 200, max_depth = 1)
gb.fit(X_train, y_train.ravel())
y_predgb = gb.predict(X_test) 

In [28]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_predgb)
cm1

array([[54,  0,  0],
       [ 0, 82,  1],
       [ 0,  0, 75]], dtype=int64)