### Importing Libraries

In [107]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [108]:
dataset = pd.read_csv('milknew.csv')

In [109]:
X = dataset.iloc[:, 3:13].values

In [110]:
y = dataset.iloc[:, 3:13].values

In [111]:
print(X)
print(y)

[[0 1 0 254 'high']
 [1 0 1 253 'high']
 [1 1 1 246 'low']
 ...
 [1 1 1 255 'low']
 [0 1 0 250 'high']
 [1 1 1 255 'low']]
[[0 1 0 254 'high']
 [1 0 1 253 'high']
 [1 1 1 246 'low']
 ...
 [1 1 1 255 'low']
 [0 1 0 250 'high']
 [1 1 1 255 'low']]


#### Encoding categorical data

In [112]:
labelencoder_X_1 = LabelEncoder()

In [113]:
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [114]:
labelencoder_X_2 = LabelEncoder()

In [115]:
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [116]:
sns.set_theme()
sns.set(rc = {'figure.figsize':(12,6)})
SEED = 2022

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#### Splitting the dataset into the Training set and Test set

In [117]:
X_train, X_test, y_train, y_test = train_test_split(
    dataset.iloc[:,:-1], 
    dataset.iloc[:,-1],
    test_size = 0.2,
    random_state = SEED
)

<IPython.core.display.Javascript object>

#### Feature Scaling

In [132]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### Adding the input layer 

In [119]:
classifier = Sequential()

In [120]:
classifier.add(Dense(6,  activation = 'relu', input_dim = 11))

In [121]:
classifier.add(Dense(6,  activation = 'relu'))

#### Adding the output layer

In [122]:
classifier.add(Dense(6,  activation = 'sigmoid', input_dim = 11))

#### Compiling the ANN

In [123]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [125]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [130]:
y_pred = lr.predict(X_test)

#### Confusion Matrix

In [127]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[44  7  1]
 [ 9 74  2]
 [10  4 61]]
